version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      - my-network
    depends_on:
      - postgres
    environment:
      - RUN_DB_INIT=true
      - DB_URL=jdbc:postgresql://postgres:5432/statzinator-db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: statzinator-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      my-network:
        aliases:
          - postgres

networks:
  my-network:
